apiVersion: v1
kind: Service
metadata:
  name: homelab-demo-app-service
  namespace: homelab-apps
spec:
  type: NodePort
  selector:
    app: homelab-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
